-- Ammo Making - renders the ammunition balance table from AC_Calibres
--
-- docs/AMMUNITION_DESIGN.md carries one table with every balance value of
-- every calibre. It is not typed by hand: this file renders it from the
-- calibre model, tests/write_recipes.lua writes it between the two marker
-- comments in the document, and tests/run_tests.lua fails while the document
-- and the model differ. The numbers therefore live in one place,
-- AC_Calibres.lua.
--
-- Returns a table of functions; it defines no globals. The mod must be
-- loaded (AC_Calibres, AC_Materials) before render() is called.

local B = {}

B.START = "<!-- BALANCE TABLE: generated by tests/write_recipes.lua from AC_Calibres.lua. Do not edit. -->"
B.FINISH = "<!-- END BALANCE TABLE -->"

local STEPS = { "dieSet", "case", "bullet", "assemble" }

local function steps(values)
    local parts = {}
    for _, step in ipairs(STEPS) do
        table.insert(parts, tostring(values[step]))
    end
    return table.concat(parts, " / ")
end

-- "x1", "x2", "x1.5": a calibre's time against the pistol default.
local function multiplier(calibre)
    local D = AC_Calibres.DEFAULTS.time
    local worst = 0
    for _, step in ipairs(STEPS) do
        worst = math.max(worst, calibre.time[step] / D[step])
    end
    return "x" .. tostring(worst)
end

function B.render()
    local C = AC_Calibres.CONFIG
    local lines = {
        "| Round | Class | Vanilla item | Case / hull | Projectile | Primer family | Powder uses | Wad | Die set | Levels | XP | Time | Time vs pistol |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local copper = C.scrapUnits / calibre.bulletsPerScrap
        table.insert(lines, "| " .. table.concat({
            calibre.id,
            calibre.class,
            "`" .. calibre.round .. "`",
            calibre.cupsPerCase .. " cup" .. (calibre.cupsPerCase > 1 and "s" or "") .. " (" .. calibre.cupsPerCase * C.cupUnits .. " brass)",
            (calibre.bulletsPerScrap == 1 and "1 scrap" or ("1/" .. calibre.bulletsPerScrap .. " scrap")) .. " (" .. copper .. " copper)",
            calibre.primerFamily,
            tostring(calibre.powderUses),
            tostring(calibre.wads),
            "`" .. calibre.dieSet .. "`",
            steps(calibre.levels),
            steps(calibre.xp),
            steps(calibre.time),
            multiplier(calibre),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- The primer families, by the same rule.
function B.renderPrimers()
    local lines = {
        "| Family | Class | Item | Brass | Compound | Per small brass sheet | Toy caps / match uses per sheet | Level | XP | Time | Rounds |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, primer in ipairs(AC_Calibres.PRIMERS) do
        local users, charges = {}, {}
        for _, calibre in ipairs(AC_Calibres.LIST) do
            if calibre.primerFamily == primer.id then table.insert(users, calibre.id) end
        end
        for _, source in ipairs(AC_Calibres.COMPOUND_SOURCES) do
            table.insert(charges, tostring(primer.perSheet * primer.compoundUnits / source.units))
        end
        table.insert(lines, "| " .. table.concat({
            primer.id,
            primer.class,
            "`" .. primer.item .. "`",
            tostring(primer.brassUnits),
            tostring(primer.compoundUnits),
            tostring(primer.perSheet),
            table.concat(charges, " / "),
            tostring(primer.requiredLevel),
            tostring(primer.xp),
            tostring(primer.time),
            table.concat(users, ", "),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- What one round holds, and what a hundred take from raw stock. Ore is
-- the brass ingots plus the copper for the projectiles (one ore is one
-- ingot of metal, ten scrap).
function B.renderMaterials()
    local C = AC_Calibres.CONFIG
    local P = AC_Calibres.POWDER
    local lines = {
        "| Round | Brass per round (case + primer) | Copper | Powder | Priming compound | Per 100: brass ingots | Copper scrap | Toy caps | Fertilizer uses | Charcoal | Wads | Ore |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local primer = AC_Calibres.getPrimer(calibre.primerFamily)
        local case = calibre.cupsPerCase * C.cupUnits
        local copper = C.scrapUnits / calibre.bulletsPerScrap
        local ingots = 100 * (case + primer.brassUnits) / AC_Materials.CONFIG.unitsPerIngot
        local scrap = 100 / calibre.bulletsPerScrap
        local mixes = 100 * calibre.powderUses / P.usesPerJar
        table.insert(lines, "| " .. table.concat({
            calibre.id,
            case .. " + " .. primer.brassUnits .. " = " .. (case + primer.brassUnits),
            tostring(copper),
            tostring(calibre.powderUses),
            tostring(primer.compoundUnits),
            tostring(ingots),
            tostring(scrap),
            tostring(100 * primer.compoundUnits / AC_Calibres.COMPOUND_SOURCES[1].units),
            tostring(mixes * P.fertilizerUses),
            -- one per forged ingot, two for the die set, and the powder's
            tostring(ingots + 2 + mixes * P.charcoal),
            tostring(100 * calibre.wads),
            tostring(ingots + scrap / 10),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- The whole generated block, markers included.
function B.renderBlock()
    return B.START .. "\n\n" .. B.render() .. "\n\n" .. B.renderPrimers() .. "\n\n" .. B.renderMaterials() .. "\n\n" .. B.FINISH
end

local function replaceBetween(text, start, finish, block)
    local from = string.find(text, start, 1, true)
    local _, to = string.find(text, finish, 1, true)
    if not from or not to or to < from then
        return nil
    end
    return string.sub(text, 1, from - 1) .. block .. string.sub(text, to + 1)
end

-- Returns text with the block between the markers replaced, or nil when
-- the markers are missing.
function B.replaceBlock(text)
    return replaceBetween(text, B.START, B.FINISH, B.renderBlock())
end

------------------------------------------------
-- The whole chain, from ore, for a batch of one calibre: what it takes and
-- what Ammo Making XP it pays. Arithmetic on the model, with fractions (a
-- brass batch is ten ingots; a hundred rounds rarely need a whole number
-- of batches), so these are equivalents, not a crafting plan. The tests
-- check them against a mirror-inventory run.
------------------------------------------------

function B.economy(calibre, rounds)
    local C = AC_Calibres.CONFIG
    local M = AC_Materials.CONFIG
    local P = AC_Calibres.POWDER
    local primer = AC_Calibres.getPrimer(calibre.primerFamily)
    local perIngot = M.unitsPerIngot

    local e = { rounds = rounds }
    e.caseCups = rounds * calibre.cupsPerCase
    e.cupSheets = e.caseCups / 2
    e.primerSheets = rounds / primer.perSheet
    e.brassIngots = rounds * (calibre.cupsPerCase * C.cupUnits + primer.brassUnits) / perIngot
    e.copperScrap = rounds / calibre.bulletsPerScrap
    -- Brass is seven parts copper to three of zinc; the projectiles are copper.
    e.copperOre = 0.7 * e.brassIngots + e.copperScrap * C.scrapUnits / perIngot
    e.zincOre = 0.3 * e.brassIngots
    e.ore = e.copperOre + e.zincOre
    e.powderJars = rounds * calibre.powderUses / P.usesPerJar
    e.fertilizerUses = e.powderJars * P.fertilizerUses
    e.compound = rounds * primer.compoundUnits
    e.toyCaps = e.compound / AC_Calibres.COMPOUND_SOURCES[1].units
    e.matchUses = e.compound / AC_Calibres.COMPOUND_SOURCES[2].units
    e.wads = rounds * calibre.wads
    -- Charcoal: 4 per ore smelted, 4 per ingot cast, 1 per ingot of the
    -- alloy batch, 1 per ingot forged into sheets, the powder's own, and 2
    -- for the die set.
    e.charcoal = 4 * e.ore + 4 * e.brassIngots + e.brassIngots + e.brassIngots + e.powderJars * P.charcoal + 2
    e.xp = {
        prospecting = e.ore / (9 * AC_Deposits.CONFIG.reserveByGrade["Moderate"]) * AC_GeologySampling.CONFIG.fieldAssayXP,
        mining = e.ore * AC_Mining.CONFIG.xpPerOre,
        -- Zinc smelting, casting both metals, the alloy (one craft per ten ingots).
        metallurgy = e.zincOre * M.xpSmeltZincOre + e.brassIngots * M.xpCastIngot + e.brassIngots / 10 * M.xpCastBrass,
        caseStock = e.brassIngots * M.xpForgeBrassSheets + e.cupSheets * M.xpPunchCaseCups,
        primers = e.primerSheets * primer.xp,
        dieSet = calibre.xp.dieSet,
        cases = rounds * calibre.xp.case,
        bullets = e.copperScrap * calibre.xp.bullet,
        powder = e.powderJars * P.xp,
        assembly = rounds * calibre.xp.assemble,
    }
    e.totalXP = 0
    for _, amount in pairs(e.xp) do e.totalXP = e.totalXP + amount end

    -- Work: how many times each thing is done, and the time of the station
    -- recipes in the recipes' own "time" units, at the level each recipe
    -- unlocks (no skill speed-up). Mining and prospecting are timed actions
    -- with a different clock and are counted, not timed.
    local R = AC_Materials.getRecipe
    local steps = {}
    for _, recipe in ipairs(AC_Calibres.buildCalibreRecipes(calibre)) do steps[recipe.step] = recipe end
    local pressSteps = {}
    for _, recipe in ipairs(AC_Calibres.buildPressRecipes(calibre)) do pressSteps[recipe.step] = recipe end
    local primerTime = primer.time
    -- { crafts, time of one craft, the press's time of one craft or nil }
    e.work = {
        -- Vanilla's own SmeltCopperOre has the time of the zinc recipe on 42.20.4.
        smelting = { e.ore, R("AmmoMaking_SmeltZincOre").time },
        casting = { e.brassIngots, R("AmmoMaking_CastCopperIngot").time },
        alloy = { e.brassIngots / 10, R("AmmoMaking_CastBrassIngots").time },
        sheets = { e.brassIngots, R("AmmoMaking_ForgeSmallBrassSheets").time },
        cups = { e.cupSheets, R("AmmoMaking_PunchBrassCaseCups").time },
        primers = { e.primerSheets, primerTime },
        dieSet = { 1, steps.dieSet.time },
        powder = { e.powderJars, P.time },
        cases = { rounds, steps.case.time, pressSteps.case and pressSteps.case.time },
        bullets = { e.copperScrap, steps.bullet.time, pressSteps.bullet and pressSteps.bullet.time },
        assembly = { rounds, steps.assemble.time, pressSteps.assemble and pressSteps.assemble.time },
    }
    e.miningActions = e.ore
    e.hotCrafts = e.work.smelting[1] + e.work.casting[1] + e.work.alloy[1] + e.work.sheets[1] + e.work.dieSet[1]
    e.benchCrafts = e.work.cups[1] + e.work.primers[1] + e.work.powder[1] + e.work.cases[1] + e.work.bullets[1] + e.work.assembly[1]
    e.crafts = e.hotCrafts + e.benchCrafts
    e.handTime, e.pressTime, e.pressableTime = 0, 0, 0
    for _, entry in pairs(e.work) do
        e.handTime = e.handTime + entry[1] * entry[2]
        e.pressTime = e.pressTime + entry[1] * (entry[3] or entry[2])
        if entry[3] then e.pressableTime = e.pressableTime + entry[1] * entry[2] end
    end
    return e
end

-- Adds one economy to another, field by field (the die set is counted
-- once per calibre, which is right for a mixed loadout).
local function addEconomy(total, e)
    for key, value in pairs(e) do
        if type(value) == "number" then
            total[key] = (total[key] or 0) + value
        elseif key == "xp" then
            total.xp = total.xp or {}
            for part, amount in pairs(value) do total.xp[part] = (total.xp[part] or 0) + amount end
        end
    end
    return total
end

-- The canonical scenarios: a hundred rounds of every calibre, and four
-- loadouts. A is a mixed kit of 200 pistol rounds, 100 rifle rounds and 50
-- shells; B, C and D are one calibre in quantity.
B.ECONOMY_CALIBRES = {}
for _, calibre in ipairs(AC_Calibres.LIST) do table.insert(B.ECONOMY_CALIBRES, calibre.id) end
B.ECONOMY_MIX = { { "9mm", 200 }, { ".308", 100 }, { "12 Gauge", 50 } }
B.ECONOMY_LOADOUTS = {
    { id = "A", label = "Mixed loadout", parts = B.ECONOMY_MIX },
    { id = "B", label = "Pistol stock", parts = { { "9mm", 500 } } },
    { id = "C", label = "Rifle stock", parts = { { ".308", 200 } } },
    { id = "D", label = "Shotgun stock", parts = { { "12 Gauge", 200 } } },
}

function B.economyOf(parts)
    local total = {}
    for _, part in ipairs(parts) do
        addEconomy(total, B.economy(AC_Calibres.get(part[1]), part[2]))
    end
    return total
end

function B.economyMix()
    return B.economyOf(B.ECONOMY_MIX)
end

local function loadoutLabel(loadout, full)
    local parts = {}
    for _, part in ipairs(loadout.parts) do table.insert(parts, part[2] .. " x " .. part[1]) end
    if full then
        return "**" .. loadout.id .. ". " .. loadout.label .. "**: " .. table.concat(parts, ", ")
    end
    return "**" .. loadout.id .. ". " .. loadout.label .. "**"
end

B.ECONOMY_START = "<!-- ECONOMY TABLE: generated by tests/write_recipes.lua from AC_Calibres.lua and AC_Materials.lua. Do not edit. -->"
B.ECONOMY_FINISH = "<!-- END ECONOMY TABLE -->"

-- "11", "9.2", "619": at most one decimal.
local function short(value)
    local rounded = math.floor(value * 10 + 0.5) / 10
    if rounded == math.floor(rounded) then return string.format("%d", rounded) end
    return string.format("%.1f", rounded)
end

function B.renderEconomy()
    local lines = {
        "| Batch | Copper ore | Zinc ore | Ore in all | Brass ingots | Copper scrap for projectiles | Case cups | Charcoal | Powder jars | Fertilizer uses (bags of 8) | Toy caps, or match uses | Wads | Ammo Making XP | XP per ore |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    }
    local function row(label, e)
        table.insert(lines, "| " .. table.concat({
            label,
            short(e.copperOre), short(e.zincOre), short(e.ore), short(e.brassIngots), short(e.copperScrap), short(e.caseCups),
            short(e.charcoal), short(e.powderJars),
            short(e.fertilizerUses) .. " (" .. short(e.fertilizerUses / 8) .. ")",
            short(e.toyCaps) .. ", or " .. short(e.matchUses),
            short(e.wads),
            short(e.totalXP),
            short(e.totalXP / e.ore),
        }, " | ") .. " |")
    end
    for _, id in ipairs(B.ECONOMY_CALIBRES) do
        row("100 x " .. id, B.economy(AC_Calibres.get(id), 100))
    end
    for _, loadout in ipairs(B.ECONOMY_LOADOUTS) do
        row(loadoutLabel(loadout, true), B.economyOf(loadout.parts))
    end

    local shares = {
        "| Batch | Prospecting | Mining | Metallurgy | Case stock | Primers | Die set | Cases | Projectiles | Powder | Assembly |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    }
    local order = { "prospecting", "mining", "metallurgy", "caseStock", "primers", "dieSet", "cases", "bullets", "powder", "assembly" }
    local function shareRow(label, e)
        local cells = { label }
        for _, part in ipairs(order) do table.insert(cells, short(e.xp[part])) end
        table.insert(shares, "| " .. table.concat(cells, " | ") .. " |")
    end
    for _, id in ipairs(B.ECONOMY_CALIBRES) do
        shareRow("100 x " .. id, B.economy(AC_Calibres.get(id), 100))
    end
    for _, loadout in ipairs(B.ECONOMY_LOADOUTS) do
        shareRow(loadoutLabel(loadout), B.economyOf(loadout.parts))
    end

    -- Work: crafts, and station time by hand and with the prepared press.
    local work = {
        "| Batch | Mining actions | Furnace and forge crafts | Surface crafts | Crafts in all | Station time by hand | With the press | Time saved | XP per 1000 time by hand | With the press |",
        "|---|---|---|---|---|---|---|---|---|---|",
    }
    local function workRow(label, e)
        -- XP earned at stations (everything but prospecting and mining).
        local stationXP = e.totalXP - e.xp.prospecting - e.xp.mining
        table.insert(work, "| " .. table.concat({
            label,
            short(e.miningActions), short(e.hotCrafts), short(e.benchCrafts), short(e.crafts),
            short(e.handTime), short(e.pressTime),
            short(100 * (e.handTime - e.pressTime) / e.handTime) .. " %",
            short(1000 * stationXP / e.handTime), short(1000 * stationXP / e.pressTime),
        }, " | ") .. " |")
    end
    for _, id in ipairs(B.ECONOMY_CALIBRES) do
        workRow("100 x " .. id, B.economy(AC_Calibres.get(id), 100))
    end
    for _, loadout in ipairs(B.ECONOMY_LOADOUTS) do
        workRow(loadoutLabel(loadout), B.economyOf(loadout.parts))
    end
    return table.concat(lines, "\n") .. "\n\n" .. table.concat(shares, "\n") .. "\n\n" .. table.concat(work, "\n")
end

function B.renderEconomyBlock()
    return B.ECONOMY_START .. "\n\n" .. B.renderEconomy() .. "\n\n" .. B.ECONOMY_FINISH
end

function B.replaceEconomy(text)
    return replaceBetween(text, B.ECONOMY_START, B.ECONOMY_FINISH, B.renderEconomyBlock())
end

------------------------------------------------
-- docs/LOOT_AND_RECYCLING.md: where a die set can be found. Rendered from
-- AC_Loot, with each list's roll count from the vanilla snapshot.
------------------------------------------------

B.LOOT_START = "<!-- LOOT TABLE: generated by tests/write_recipes.lua from AC_Loot.lua. Do not edit. -->"
B.LOOT_FINISH = "<!-- END LOOT TABLE -->"

local function percent(value)
    return string.format("%.2f %%", value)
end

-- vanilla: the table tests/vanilla_snapshot.lua returns.
function B.renderLoot(vanilla)
    local lines = {
        "| Loot list | Filled from it | Die sets | Weight each | Chance per container, each | Chance per container, any die set |",
        "|---|---|---|---|---|---|",
    }
    for _, target in ipairs(AC_Loot.TARGETS) do
        local rolls = vanilla.loot.lists[target.list].rolls
        local names, weights, chances, total = {}, {}, {}, 0
        local seen = {}
        for _, entry in ipairs(AC_Loot.buildEntries({ target })) do
            table.insert(names, entry.calibre)
            total = total + entry.weight
            if not seen[entry.weight] then
                seen[entry.weight] = true
                table.insert(weights, tostring(entry.weight))
                table.insert(chances, percent(AC_Loot.chancePerContainer(entry.weight, rolls)))
            end
        end
        table.insert(lines, "| " .. table.concat({
            "`" .. target.list .. "`",
            target.where,
            table.concat(names, ", "),
            table.concat(weights, " / "),
            table.concat(chances, " / "),
            percent(AC_Loot.chancePerContainer(total, rolls)),
        }, " | ") .. " |")
    end

    local tiers = {
        "| Die set | Tier | Lists |",
        "|---|---|---|",
    }
    local entries = AC_Loot.buildEntries()
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local lists = {}
        for _, entry in ipairs(entries) do
            if entry.item == calibre.dieSet then table.insert(lists, "`" .. entry.list .. "` " .. entry.weight) end
        end
        table.insert(tiers, "| " .. calibre.id .. " | " .. tostring(calibre.lootTier) .. " | " .. table.concat(lists, ", ") .. " |")
    end
    return table.concat(lines, "\n") .. "\n\n" .. table.concat(tiers, "\n")
end

function B.renderLootBlock(vanilla)
    return B.LOOT_START .. "\n\n" .. B.renderLoot(vanilla) .. "\n\n" .. B.LOOT_FINISH
end

function B.replaceLoot(text, vanilla)
    return replaceBetween(text, B.LOOT_START, B.LOOT_FINISH, B.renderLootBlock(vanilla))
end

------------------------------------------------
-- docs/LOOT_AND_RECYCLING.md: what can be scrapped and what comes back.
-- Rendered from AC_Recycling and the material units.
------------------------------------------------

B.RECYCLING_START = "<!-- RECYCLING TABLE: generated by tests/write_recipes.lua from AC_Recycling.lua. Do not edit. -->"
B.RECYCLING_FINISH = "<!-- END RECYCLING TABLE -->"

function B.renderRecycling()
    local scrapUnits = AC_Materials.UNITS[AC_Recycling.CONFIG.scrapItem].units
    local lines = {
        "| Recipe | Takes (any mix of) | Per craft | Brass in | Brass scrap out | Brass out | Lost | Level | XP |",
        "|---|---|---|---|---|---|---|---|---|",
    }
    for _, group in ipairs(AC_Recycling.buildGroups()) do
        local items = {}
        for _, itemType in ipairs(group.items) do table.insert(items, "`" .. itemType .. "`") end
        local brassIn, brassOut = group.count * group.units, group.scrap * scrapUnits
        table.insert(lines, "| " .. table.concat({
            "`" .. AC_Recycling.CONFIG.idPrefix .. group.units .. "`",
            table.concat(items, ", "),
            tostring(group.count),
            tostring(brassIn),
            tostring(group.scrap),
            tostring(brassOut),
            tostring(brassIn - brassOut),
            tostring(AC_Recycling.CONFIG.requiredLevel),
            tostring(AC_Recycling.CONFIG.xp),
        }, " | ") .. " |")
    end
    local C = AC_Recycling.CONFIG
    table.insert(lines, "| " .. table.concat({
        "`" .. C.castId .. "`",
        "`" .. C.scrapItem .. "`",
        tostring(C.scrapPerIngot),
        tostring(C.scrapPerIngot * scrapUnits),
        "1 `" .. C.ingotItem .. "`",
        tostring(C.ingotUnits),
        tostring(C.scrapPerIngot * scrapUnits - C.ingotUnits),
        tostring(C.requiredLevel),
        tostring(C.xp),
    }, " | ") .. " |")
    return table.concat(lines, "\n")
end

function B.renderRecyclingBlock()
    return B.RECYCLING_START .. "\n\n" .. B.renderRecycling() .. "\n\n" .. B.RECYCLING_FINISH
end

function B.replaceRecycling(text)
    return replaceBetween(text, B.RECYCLING_START, B.RECYCLING_FINISH, B.renderRecyclingBlock())
end

------------------------------------------------
-- docs/DEVELOPMENT.md: every recipe of the mod by family, with the ranges
-- of what a craft needs and pays. Rendered from AC_Materials.RECIPES.
------------------------------------------------

B.AUDIT_START = "<!-- RECIPE AUDIT TABLE: generated by tests/write_recipes.lua from AC_Materials.RECIPES. Do not edit. -->"
B.AUDIT_FINISH = "<!-- END RECIPE AUDIT TABLE -->"

local FAMILIES = {
    { "metallurgy", "Metallurgy (ore to brass)" },
    { "caseStock", "Case stock (sheets, cups)" },
    { "powder", "Gunpowder" },
    { "primer", "Primers" },
    { "dieSet", "Die sets" },
    { "case", "Cases and hulls" },
    { "bullet", "Bullets and shot" },
    { "assemble", "Assembly" },
    { "scrap", "Scrapping brass" },
    { "recast", "Recasting brass scrap" },
}

function B.recipeFamily(recipe)
    if recipe.step then return recipe.step end
    if recipe.benchTag == "PrimitiveFurnace" or recipe.benchTag == "Furnace" then return "metallurgy" end
    return "caseStock"
end

-- "5", or "1 to 3".
local function range(low, high)
    if low == high then return tostring(low) end
    return low .. " to " .. high
end

function B.renderRecipeAudit()
    local lines = {
        "| Family | Recipes | Station tags | Ammo Making level | XP per craft | Time | Kept tools | Consumed lines | Output lines |",
        "|---|---|---|---|---|---|---|---|---|",
    }
    local total = 0
    for _, family in ipairs(FAMILIES) do
        local count, stations, seen = 0, {}, {}
        local level, xp, time, kept, consumed, outputs = {}, {}, {}, {}, {}, {}
        local function note(bucket, value)
            bucket.low = math.min(bucket.low or value, value)
            bucket.high = math.max(bucket.high or value, value)
        end
        for _, recipe in ipairs(AC_Materials.RECIPES) do
            if B.recipeFamily(recipe) == family[1] then
                count = count + 1
                if not seen[recipe.benchTag] then
                    seen[recipe.benchTag] = true
                    table.insert(stations, "`" .. recipe.benchTag .. "`")
                end
                note(level, AC_Materials.getRequiredLevel(recipe))
                note(xp, AC_Materials.getRecipeXP(recipe))
                note(time, recipe.time)
                local keptLines, consumedLines = 0, 0
                for _, input in ipairs(recipe.inputs) do
                    if input.keep then keptLines = keptLines + 1 else consumedLines = consumedLines + 1 end
                end
                note(kept, keptLines)
                note(consumed, consumedLines)
                note(outputs, #recipe.outputs)
            end
        end
        total = total + count
        table.insert(lines, "| " .. table.concat({
            family[2], tostring(count), table.concat(stations, ", "),
            range(level.low, level.high), range(xp.low, xp.high), range(time.low, time.high),
            range(kept.low, kept.high), range(consumed.low, consumed.high), range(outputs.low, outputs.high),
        }, " | ") .. " |")
    end
    table.insert(lines, "| **All** | **" .. total .. "** | | | | | | | |")
    return table.concat(lines, "\n")
end

function B.renderRecipeAuditBlock()
    return B.AUDIT_START .. "\n\n" .. B.renderRecipeAudit() .. "\n\n" .. B.AUDIT_FINISH
end

function B.replaceRecipeAudit(text)
    return replaceBetween(text, B.AUDIT_START, B.AUDIT_FINISH, B.renderRecipeAuditBlock())
end

------------------------------------------------
-- README.md carries a shorter table of the same model, for players.
------------------------------------------------

B.SUMMARY_START = "<!-- CALIBRE TABLE: generated by tests/write_recipes.lua from AC_Calibres.lua. Do not edit. -->"
B.SUMMARY_FINISH = "<!-- END CALIBRE TABLE -->"

-- "SmallPistol" -> "small pistol"
local function spaced(name)
    return string.lower((string.gsub(name, "(%l)(%u)", "%1 %2")))
end

function B.renderSummary()
    local C = AC_Calibres.CONFIG
    local lines = {
        "| Round | Type | Vanilla item | Primer | Cups per case | Projectiles per scrap | Powder charges | Wads | Round at level | Ore per 100 rounds |",
        "|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local primer = AC_Calibres.getPrimer(calibre.primerFamily)
        local brass = calibre.cupsPerCase * C.cupUnits + primer.brassUnits
        table.insert(lines, "| " .. table.concat({
            calibre.id,
            calibre.class,
            "`" .. calibre.round .. "`",
            spaced(calibre.primerFamily),
            tostring(calibre.cupsPerCase),
            tostring(calibre.bulletsPerScrap),
            tostring(calibre.powderUses),
            tostring(calibre.wads),
            tostring(calibre.levels.assemble),
            tostring(100 * brass / AC_Materials.CONFIG.unitsPerIngot + 100 / calibre.bulletsPerScrap / 10),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

function B.renderSummaryBlock()
    return B.SUMMARY_START .. "\n\n" .. B.renderSummary() .. "\n\n" .. B.SUMMARY_FINISH
end

function B.replaceSummary(text)
    return replaceBetween(text, B.SUMMARY_START, B.SUMMARY_FINISH, B.renderSummaryBlock())
end

return B
