-- Ammo Making - renders the ammunition balance table from AC_Calibres
--
-- docs/AMMUNITION_DESIGN.md carries one table with every balance value of
-- every calibre. It is not typed by hand: this file renders it from the
-- calibre model, tests/write_recipes.lua writes it between the two marker
-- comments in the document, and tests/run_tests.lua fails while the document
-- and the model differ. The numbers therefore live in one place,
-- AC_Calibres.lua.
--
-- Returns a table of functions; it defines no globals. The mod must be
-- loaded (AC_Calibres, AC_Materials) before render() is called.

local B = {}

B.START = "<!-- BALANCE TABLE: generated by tests/write_recipes.lua from AC_Calibres.lua. Do not edit. -->"
B.FINISH = "<!-- END BALANCE TABLE -->"

local STEPS = { "dieSet", "case", "bullet", "assemble" }

local function steps(values)
    local parts = {}
    for _, step in ipairs(STEPS) do
        table.insert(parts, tostring(values[step]))
    end
    return table.concat(parts, " / ")
end

-- "x1", "x2", "x1.5": a calibre's time against the pistol default.
local function multiplier(calibre)
    local D = AC_Calibres.DEFAULTS.time
    local worst = 0
    for _, step in ipairs(STEPS) do
        worst = math.max(worst, calibre.time[step] / D[step])
    end
    return "x" .. tostring(worst)
end

function B.render()
    local C = AC_Calibres.CONFIG
    local lines = {
        "| Round | Class | Vanilla item | Case / hull | Projectile | Primer family | Powder uses | Wad | Die set | Levels | XP | Time | Time vs pistol |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local copper = C.scrapUnits / calibre.bulletsPerScrap
        table.insert(lines, "| " .. table.concat({
            calibre.id,
            calibre.class,
            "`" .. calibre.round .. "`",
            calibre.cupsPerCase .. " cup" .. (calibre.cupsPerCase > 1 and "s" or "") .. " (" .. calibre.cupsPerCase * C.cupUnits .. " brass)",
            (calibre.bulletsPerScrap == 1 and "1 scrap" or ("1/" .. calibre.bulletsPerScrap .. " scrap")) .. " (" .. copper .. " copper)",
            calibre.primerFamily,
            tostring(calibre.powderUses),
            tostring(calibre.wads),
            "`" .. calibre.dieSet .. "`",
            steps(calibre.levels),
            steps(calibre.xp),
            steps(calibre.time),
            multiplier(calibre),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- The primer families, by the same rule.
function B.renderPrimers()
    local lines = {
        "| Family | Class | Item | Brass | Compound | Per small brass sheet | Toy caps / match uses per sheet | Level | XP | Time | Rounds |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, primer in ipairs(AC_Calibres.PRIMERS) do
        local users, charges = {}, {}
        for _, calibre in ipairs(AC_Calibres.LIST) do
            if calibre.primerFamily == primer.id then table.insert(users, calibre.id) end
        end
        for _, source in ipairs(AC_Calibres.COMPOUND_SOURCES) do
            table.insert(charges, tostring(primer.perSheet * primer.compoundUnits / source.units))
        end
        table.insert(lines, "| " .. table.concat({
            primer.id,
            primer.class,
            "`" .. primer.item .. "`",
            tostring(primer.brassUnits),
            tostring(primer.compoundUnits),
            tostring(primer.perSheet),
            table.concat(charges, " / "),
            tostring(primer.requiredLevel),
            tostring(primer.xp),
            tostring(primer.time),
            table.concat(users, ", "),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- What one round holds, and what a hundred take from raw stock. Ore is
-- the brass ingots plus the copper for the projectiles (one ore is one
-- ingot of metal, ten scrap).
function B.renderMaterials()
    local C = AC_Calibres.CONFIG
    local P = AC_Calibres.POWDER
    local lines = {
        "| Round | Brass per round (case + primer) | Copper | Powder | Priming compound | Per 100: brass ingots | Copper scrap | Toy caps | Fertilizer uses | Charcoal | Wads | Ore |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    }
    for _, calibre in ipairs(AC_Calibres.LIST) do
        local primer = AC_Calibres.getPrimer(calibre.primerFamily)
        local case = calibre.cupsPerCase * C.cupUnits
        local copper = C.scrapUnits / calibre.bulletsPerScrap
        local ingots = 100 * (case + primer.brassUnits) / AC_Materials.CONFIG.unitsPerIngot
        local scrap = 100 / calibre.bulletsPerScrap
        local mixes = 100 * calibre.powderUses / P.usesPerJar
        table.insert(lines, "| " .. table.concat({
            calibre.id,
            case .. " + " .. primer.brassUnits .. " = " .. (case + primer.brassUnits),
            tostring(copper),
            tostring(calibre.powderUses),
            tostring(primer.compoundUnits),
            tostring(ingots),
            tostring(scrap),
            tostring(100 * primer.compoundUnits / AC_Calibres.COMPOUND_SOURCES[1].units),
            tostring(mixes * P.fertilizerUses),
            -- one per forged ingot, two for the die set, and the powder's
            tostring(ingots + 2 + mixes * P.charcoal),
            tostring(100 * calibre.wads),
            tostring(ingots + scrap / 10),
        }, " | ") .. " |")
    end
    return table.concat(lines, "\n")
end

-- The whole generated block, markers included.
function B.renderBlock()
    return B.START .. "\n\n" .. B.render() .. "\n\n" .. B.renderPrimers() .. "\n\n" .. B.renderMaterials() .. "\n\n" .. B.FINISH
end

-- Returns text with the block between the markers replaced, or nil when
-- the markers are missing.
function B.replaceBlock(text)
    local from = string.find(text, B.START, 1, true)
    local _, to = string.find(text, B.FINISH, 1, true)
    if not from or not to or to < from then
        return nil
    end
    return string.sub(text, 1, from - 1) .. B.renderBlock() .. string.sub(text, to + 1)
end

return B
